name: Deploy HTML/CSS/JS to GitHub Pages

on:
  pull_request:
    branches:
      - main  # branch bạn muốn deploy  
  workflow_dispatch:  # cho phép chạy thủ công từ tab Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy Buoi7 to GitHub Pages folder
        run: |
          mkdir -p public
          cp -r Buoi7/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public